### ISSUE TITLE
Job Manager is not scalable for high numbers of workflows

### ISSUE THREAD

**Issue by rhiananthony** [DataBiosphere/job-manager#544] opened 2019-01-11 18:50 UTC
We are experiencing a problem with the job manager in gotc-prod. We believe that this is due to the high number of workflows that are being returned by cromwell in gotc-prod, and then job manager is dying at the API level when it tries to paginate the large data set. 

The URL for the job manager can be found here:
https://job-manager.gotc-prod.broadinstitute.org/jobs

The username and password are in vault, located at the following path:
secret/dsde/gotc/prod/job-manager/htpasswd

**Comment by rsasch** [comment] 2019-01-11 19:18
What version of Job Manager is gotc-prod running?

**Comment by rsasch** [comment] 2019-01-11 20:18
Are there logs or other things that lead you to believe that it's failing at the API level?

**Comment by rsasch** [comment] 2019-01-15 20:13
@rhiananthony @pshapiro4broad Not a solution, but a workaround:
1. Navigate to https://job-manager.gotc-prod.broadinstitute.org/jobs?q=status%3DRunning
you will hopefully see an empty list (which is not accurate)
2. Change the "Items per page" value 
3. Remove the "Running" chip
When I did this, I was able to use the UI as expected.

**Comment by rsasch** [comment] 2019-01-15 20:18
This makes me think it isn't a scalability issue, but something else.

**Comment by cjllanwarne** [comment] 2019-01-16 21:10
@rhiananthony 

- How many workflows makes you think that it's "too many" in this context?

- What version of Cromwell are you pointed at? I know some changes happened recently to improve pagination and query performance in general

- Could you try a `query` to Cromwell itself with the pagination set? With parameters something like this?
```json
[
  {
    "includeSubworkflows": "false",
    "page": "1",
    "pageSize": "50"
  }
]
```
If that fails, I believe this is a Cromwell, rather than Job Manager bug and I'll move it to the other repo.

**Comment by cjllanwarne** [comment] 2019-01-17 17:15
@rhiananthony @rsasch @pshapiro4broad - I'm closing this as an issue in JobManager because the root cause is in Cromwell's inability to respond to these queries on time. 

For progress you can watch the Cromwell issue  https://github.com/broadinstitute/cromwell/issues/4561 which I'm picking up now, and be aware that the fix will require you to update to the Cromwell version containing the fix, as and when it appears.

Thanks!

**Closed by cjllanwarne** 2019-01-17 17:15 UTC
