### ISSUE TITLE
Friendlier message for "No Cromwell Service Running"

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#311] opened 2018-07-05 14:50 UTC
Imagine me being foolish enough to fire up JMUI without turning on Cromwell!

Currently I see this:
<kbd>
<img width="458" alt="screen shot 2018-07-05 at 10 46 30 am" src="https://user-images.githubusercontent.com/13006282/42330251-bf9bee06-8040-11e8-8f36-26bb7f3400fb.png">
</kbd>

Ultimately I think a "status" page with (in this case) a big cross next to "Cromwell Service" would be nice. For now maybe just a page to indicate that "JMUI is working but can't reach the backend service"

**Comment by rsasch** [comment] 2018-10-31 16:36
duplicate of #442

**Closed by rsasch** 2018-10-31 16:36 UTC
